[versions]
androidGradlePlugin = "8.2.1"

[libraries]
compose-ui = "androidx.compose.ui:ui:1.5.4"
compose-foundation = "androidx.compose.foundation:foundation:1.5.4"
compose-material = "androidx.compose.material:material:1.6.0"
tools-compose-compiler = "androidx.compose.compiler:compiler:1.5.8"

sample-material = "com.google.android.material:material:1.11.0"
sample-composeActivity = "androidx.activity:activity-compose:1.8.2"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin = "org.jetbrains.kotlin.android:1.9.22"
