[libraries]
compose-ui = "androidx.compose.ui:ui:1.4.3"
compose-foundation = "androidx.compose.foundation:foundation:1.4.3"
compose-material = "androidx.compose.material:material:1.4.3"
tools-compose-compiler = "androidx.compose.compiler:compiler:1.4.7"

sample-material = "com.google.android.material:material:1.9.0"
sample-composeActivity = "androidx.activity:activity-compose:1.7.1"

[plugins]
androidApplication = "com.android.application:8.0.1"
androidLibrary = "com.android.library:8.0.2"
kotlin = "org.jetbrains.kotlin.android:1.8.21"