[versions]
androidGradlePlugin = "8.1.2"

[libraries]
compose-ui = "androidx.compose.ui:ui:1.5.3"
compose-foundation = "androidx.compose.foundation:foundation:1.5.3"
compose-material = "androidx.compose.material:material:1.5.3"
tools-compose-compiler = "androidx.compose.compiler:compiler:1.5.3"

sample-material = "com.google.android.material:material:1.10.0"
sample-composeActivity = "androidx.activity:activity-compose:1.8.0"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin = "org.jetbrains.kotlin.android:1.9.10"
wrapperUpgrade = "org.gradle.wrapper-upgrade:0.11.4"
