name: 'Build'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/jdks
          key: gradle-caches-build-v0-${{ hashFiles('gradle/libs.versions.toml', 'gradle/wrapper/gradle-wrapper.properties') }}

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Assemble
        run: ./gradlew assemble
